/**
 * Generated by jirafa types -t volar
 * Types for Volar
 */

import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    JButton: typeof import('jirafa')['JButton']
    JButtonGroup: typeof import('jirafa')['JButtonGroup']
    JDivider: typeof import('jirafa')['JDivider']
    JConfigProvider: typeof import('jirafa')['JConfigProvider']
    JRow: typeof import('jirafa')['JRow']
    JCol: typeof import('jirafa')['JCol']
    JGrid: typeof import('jirafa')['JGrid']
    JGridItem: typeof import('jirafa')['JGridItem']
    JIcon: typeof import('jirafa')['JIcon']
    JIconFeedback: typeof import('jirafa')['JIconFeedback']
    JForm: typeof import('jirafa')['JForm']
    JFormItem: typeof import('jirafa')['JFormItem']
    JInput: typeof import('jirafa')['JInput']
    JRadio: typeof import('jirafa')['JRadio']
    JRadioGroup: typeof import('jirafa')['JRadioGroup']
    JSpace: typeof import('jirafa')['JSpace']
    JTag: typeof import('jirafa')['JTag']
  }
}

export {}
