/**
 * Generated by jirafa types -t volar
 * Types for Volar
 */

import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    JButton: typeof import('../packages/jirafa')['JButton']
    JButtonGroup: typeof import('../packages/jirafa')['JButtonGroup']
    JDivider: typeof import('../packages/jirafa')['JDivider']
    JRow: typeof import('../packages/jirafa')['JRow']
    JCol: typeof import('../packages/jirafa')['JCol']
    JGrid: typeof import('../packages/jirafa')['JGrid']
    JGridItem: typeof import('../packages/jirafa')['JGridItem']
    JIcon: typeof import('../packages/jirafa')['JIcon']
    JSpace: typeof import('../packages/jirafa')['JSpace']
    JTag: typeof import('../packages/jirafa')['JTag']
  }
}

export {}
